### ISSUE TITLE
Bug - merge build fails when building netmap after merge #20

### ISSUE THREAD

**Issue by fklassen** [appneta/tcpreplay#21]
After merge get the following error

```
gcc -DHAVE_CONFIG_H -I. -I../../src    -I.. -I../..   -D_U_="__attribute__((unused))"  -Wall -O3 -std=gnu99 -Wextra -Wno-variadic-macros -Wfatal-errors -I/usr/include -I/usr/src/netmap-backup//sys -MT sendpacket.o -MD -MP -MF .deps/sendpacket.Tpo -c -o sendpacket.o sendpacket.c
sendpacket.c: In function ‘sendpacket_open’:
sendpacket.c:515: error: ‘sendpacket_type’ undeclared (first use in this function)
compilation terminated due to -Wfatal-errors.
make[4]: *** [sendpacket.o] Error 1
make[4]: Leaving directory `/home/fklassen/git/tcpreplay/src/common'
make[3]: *** [all] Error 2
make[3]: Leaving directory `/home/fklassen/git/tcpreplay/src/common'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/fklassen/git/tcpreplay/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/fklassen/git/tcpreplay/src'
```
