### ISSUE TITLE
Missing symbol _pcap_version on macOS 10.12.4

### ISSUE THREAD

**Issue by theirix** [appneta/tcpreplay#353]
Hello! Got an error for tcpreplay running on a latest macos due to missing pcap symbol. The same binary worked well on a previous version 10.12.3.

Error:
`dyld: Symbol not found: _pcap_version
  Referenced from: /Users/irix/Downloads/tcpreplay-4.2.1/./src/tcpreplay
  Expected in: /usr/lib/libpcap.A.dylib
 in /Users/irix/Downloads/tcpreplay-4.2.1/./src/tcpreplay
zsh: abort      ./src/tcpreplay`

This symbol is missing from the libpcap:
`nm /usr/lib/libpcap.A.dylib | grep pcap_ver
0000000000025df0 s _pcap_version_string`

I found an old libpcap library from 10.7 and it had the symbol:
`% nm 10.7/libpcap.A.dylib | grep pcap_vers
0000000000031394 D _pcap_version`

Configure says:
checking for pcap_version... yes

Full log:
[configure.txt](https://github.com/appneta/tcpreplay/files/879370/configure.txt)

config.log:
[config.log.gz](https://github.com/appneta/tcpreplay/files/879380/config.log.gz)

**Comment by fklassen** [comment]
@theirix it appears that your libpcap install is messed up. On my machine, `config.log` contains this...

```
configure:19923: checking for libpcap
configure:20217: result: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr
```

... but on your machine you are picking up a copy of libpcap in `/usr/lib`

```
configure:19923: checking for libpcap
configure:20217: result: /usr
```

So, there appears to be a non-standard install of libpcap on your system. Not sure how it got there. If you used Home Brew it would be installed in `/usr/local` not `/usr`. Note that on MAC, you should not install anything in `/usr`. That is for Apple. And when you install in `/usr/local`, do not use `sudo`.

Best would be to manually remove your libpcap install (if possible) and let tcpreplay pick up one installed by brew, or picked up in Xcode SDK.

**Comment by theirix** [comment]
@fklassen just to clarify things – I just updated all my tools (xcode was a version behind of command line tools). MacOS for several years at least stores the same copies of `/usr/include` in `/usr` and in  `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr`. So it should not be a problem. Library `libpcap.A.dylib` is stored only in `/usr/lib` and it is a system dependency not mine. It is the same for several 10.2.4 installations I have access to. And it seems Apple removed private 'pcap_version' symbol in this version.

I configured tcpreplay without prefix just to show a problem. Surely I never intended to install it to `/usr`. Actually I'm fixing a homebrew package problem.

I found a problem in configure script around `have_pcap_version=no`. Calling `AC_TRY_COMPILE` is not sufficient and `AC_TRY_LINK` must be called.
I run a conftest manually:
`/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -m64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -D_U_="__attribute__((unused))" -Wall -std=gnu99 -Wno-macro-redefined -Wno-variadic-macros -Wfatal-errors -I/usr/include -c x.c -lpcap`
It compiles but failed to link:
`Undefined symbols for architecture x86_64:
  "_pcap_version", referenced from:
      _main in x-a688a6.o
ld: symbol(s) not found for architecture x86_64`

Using `AC_TRY_LINK` leads to setting `have_pcap_version` to no and to linking a working binary.
Could you please accept [a patch](https://gist.github.com/c93a5f0f850af27339b2bb8c82220f58) and release a bugfix release?

**Comment by fklassen** [comment]
@theirix thanks for clarifying. Seeing your patch, I can understand how my machine accepts the compile and yours does not.

I'll test on a new installation and schedule for next bug release.

**Comment by fklassen** [comment]
released fix in [v4.2.2-beta1](https://github.com/appneta/tcpreplay/releases/tag/v4.2.2-beta1). Will release with a week.

**Comment by theirix** [comment]
Great, thank you!

**Comment by fklassen** [comment]
Fixed in 4.2.2
