### ISSUE TITLE
[Bug] PR #682 multiple directory fails to build on 32-bit PPC 

### ISSUE THREAD

**Issue by fklassen** [appneta/tcpreplay#696]
**To Reproduce**
1. start 32-bit PPC 
2. attempt to build

**Expected behavior**
should build

**Actual behavior**

```
...
make[3]: Entering directory `/home/user/tcpreplay-4.4.0-beta2/src'
  CC             tcpreplay-tcpreplay.o
In file included from tcpreplay.c:30:0:
/usr/includd/fts.h:41:3: error: #error "<fts.h> cannot be used with -D_FILE_OFFSET_BITS==64"
```

**System (please complete the following information):**
 - OS: Linux Debian PPC
 - OS version: 3.2.51-1
 - Tcpreplay Version: 4.4.0-beta2

Introduced by PR #682 and staged in #692.

**Comment by fklassen** [comment]
fixed in PR #697
