### ISSUE TITLE
[Bug] AF_XDP compile failures

### ISSUE THREAD

**Issue by fklassen** [appneta/tcpreplay#876]
**Describe the bug**
This fails to compile in 4.5.0-beta1

**To Reproduce**
1. sudo apt install -y libxdp-dev libbpf-dev
2. ./configure
3. make

**Expected behavior**
compiles

**Screenshots**
```
  CCLD     tcpreplay
/usr/bin/ld: tcpreplay-send_packets.o: in function `check_packet_fits_in_umem_frame':
/home/fklassen/git/tcpreplay/build/src/../../src/send_packets.c:1262: undefined reference to `free_umem_and_xsk
```

**System (please complete the following information):**
 - OS: Linux Debian
 - OS version: Buster
 - Tcpreplay Version: 4.5.0-beta1

**Additional context**
something got dropped in the merge

**Comment by fklassen** [comment]
fixed in PR #877
